_wandb:
    value:
        cli_version: 0.21.1
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 105
            "3":
                - 15
                - 16
            "4": 3.12.9
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-x86_64
api_key_set:
    value: true
architecture:
    value: proxy-validator-miner
monitoring:
    value: true
subnet_name:
    value: inference-subnet
version:
    value: 1.0.0
